'Author: Blagovest Zlatev
Option Explicit

Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swDraw As SldWorks.DrawingDoc
Dim swView As SldWorks.View
Dim swFeat As SldWorks.Feature

Dim configurationNames As Variant
Dim collectionPartInfo As New Collection
Dim Part As CustomPartInfo

Sub setAsm(vComponents As Variant, Part As CustomPartInfo)
    If (Not IsEmpty(vComponents)) Then
        Dim counter As Integer
        Dim swComponent As Object
                            
        For counter = 0 To UBound(vComponents)
            Set swComponent = vComponents(counter)
            If Not swComponent Is Nothing Then
                'DEBUGGING
                'Debug.Print "PartEnding = " & Right(swComponent.GetPathName, 3)
                'END_DEBUGGING
                                    
                If (Right(swComponent.GetPathName, 3) = "ASM") Then
                    Part.SetAsmPart (True)
                End If
            End If
        Next
    End If
End Sub

Function setBomTableAnnotation(sView As SldWorks.View) As SldWorks.BomTableAnnotation
    Dim bomTblAnnotation As SldWorks.BomTableAnnotation
    Dim bomStandard As String
    
    bomStandard = "C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\lang\english\bom-standard.sldbomtbt"
    Set bomTblAnnotation = sView.InsertBomTable3(False, 0, 0, swBOMConfigurationAnchor_BottomLeft, swBomType_TopLevelOnly, configurationNames(0), bomStandard, False)
    
    bomTblAnnotation.BomFeature.SetConfigurations True, True, configurationNames
    bomTblAnnotation.BomFeature.DisplayAsOneItem = True
    bomTblAnnotation.BomFeature.PartConfigurationGrouping = 1
    Set setBomTableAnnotation = bomTblAnnotation
    Exit Function
End Function

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swDraw = swModel
    
    
    Dim drawingPath As String
    Dim asmPath As String
    Dim index As Long
    Dim swTblAnnotation As SldWorks.TableAnnotation
    Dim itemNumber As String
    Dim lowestItemNumber As String
    Dim partNumber As String
    
    If Not swModel Is Nothing Then
        drawingPath = swModel.GetPathName
        
        'DEBUGGING
        Debug.Print "Success = " & swModel.GetPathName
        'END_DEBUGGING
    End If
        
        
    Set swView = swDraw.GetFirstView
    Set swView = swView.GetNextView
    
    If Not swView Is Nothing Then
        asmPath = swView.GetReferencedModelName
        
        'DEBUGGING
        Debug.Print "Success = " & swView.GetReferencedModelName
        'END_DEBUGGING
        
        Set swModel = swApp.ActivateDoc3(asmPath, False, 0, 0)
        configurationNames = swModel.GetConfigurationNames
        swView.SetVisible False, False
        Set swModel = swApp.ActivateDoc3(drawingPath, False, 0, 0)
    End If
            
    Dim bomTblAnnotation As SldWorks.BomTableAnnotation
    Set bomTblAnnotation = setBomTableAnnotation(swView)
    Set swTblAnnotation = bomTblAnnotation
            
    lowestItemNumber = "0"
    itemNumber = "1"
        
    Dim i As Integer
    Dim j As Integer
    Dim k As Integer
    Dim itemNumberForChecking As String
        
    'DEBUGGING
    'Debug.Print "ConfigName: " & configurationNames(index)
    'Debug.Print "View: " & swView.GetName2
    'Debug.Print "Count: " & bomTblAnnotation.GetComponentsCount2(1, configurationNames(1), itemNumber, partNumber)
    'Debug.Print "Table Columns: " & swTblAnnotation.ColumnCount & " Table Rows: " & swTblAnnotation.RowCount
    'END_DEBUGGING
                                    
                                    
    'DEBUGGING
    'Debug.Print "--------------------------" & configurationNames(i) & "--------------------------"
    'END_DEBUGGING

    Set Part = New CustomPartInfo
    For i = 0 To swTblAnnotation.RowCount - 1
        bomTblAnnotation.GetModelPathNames i, itemNumber, partNumber
        'DEBUGGING
        'Debug.Print "I: " & i & " itemNumber: " & itemNumber & " PartNumber: " & partNumber
        'END_DEBUGGING
        If (lowestItemNumber < itemNumber) Then
            lowestItemNumber = itemNumber
            'DEBUGGING
            'Debug.Print "--------I: " & i & " itemNumber: " & itemNumber & " PartNumber: " & partNumber
            'END_DEBUGGING
            If (i > 1) Then
                collectionPartInfo.Add Part
                'DEBUGGING
                'Debug.Print "Part Added: " & Part.GetItemNumber & " KEY: " & itemNumber
                'END_DEBUGGING
                Set Part = New CustomPartInfo
            End If
                    
            For j = i To swTblAnnotation.RowCount - 1
                bomTblAnnotation.GetModelPathNames j, itemNumberForChecking, partNumber
                If (lowestItemNumber <> itemNumberForChecking) Then
                    Exit For
                End If
                Part.SetItemNumber (itemNumberForChecking)
                Part.AddPartNames (partNumber)
                
                For k = 0 To UBound(configurationNames)
                        Dim x As Integer
                        x = bomTblAnnotation.GetComponentsCount2(j, configurationNames(k), itemNumberForChecking, partNumber)
                        Part.SetPartCount x, CStr(configurationNames(k)), partNumber
                Next k
                'DEBUGGING
                'Debug.Print "Part Count: " & x & " ItemNumber: " & itemNumber & " PartNumber: " & partNumber
                'END_DEBUGGING
            Next j
            'DEBUGGING
            'Debug.Print "I: " & i & " LOWEST ITEM NUMBER: " & lowestItemNumber
            'END_DEBUGGING
        End If
    Next i
    
    On Error Resume Next
        collectionPartInfo.Add Part
        'DEBUGGING
        Debug.Print "Part Added: " & Part.GetItemNumber & " KEY: " & itemNumber
    On Error GoTo 0
        
    For i = 1 To collectionPartInfo.Count
        'DEBUGGING
        Debug.Print "--------------------------PART " & i & "--------------------------"
        collectionPartInfo(i).PrintInfoInDebug
        'END_DEBUGGING
    Next
    
    Dim swFeat As SldWorks.Feature
    Dim swBomFeat As SldWorks.BomFeature
    Set swTblAnnotation = bomTblAnnotation
    swModel.ForceRebuild3 (True)
End Sub

