Option Explicit

Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2
Dim swDraw As SldWorks.DrawingDoc
Dim swView As SldWorks.View
Dim swFeat As SldWorks.Feature

Dim configurationNames As Variant
Dim collectionPartInfo As New Collection

Sub setAsm(vComponents As Variant, Part As CustomPartInfo)
    If (Not IsEmpty(vComponents)) Then
        Dim counter As Integer
        Dim swComponent As Object
                            
        For counter = 0 To UBound(vComponents)
            Set swComponent = vComponents(counter)
            If Not swComponent Is Nothing Then
                'DEBUGGING
                'Debug.Print "PartEnding = " & Right(swComponent.GetPathName, 3)
                'END_DEBUGGING
                                    
                If (Right(swComponent.GetPathName, 3) = "ASM") Then
                    Part.SetAsmPart (True)
                End If
            End If
        Next
    End If
End Sub

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swDraw = swModel
    
    
    Dim drawingPath As String
    Dim asmPath As String
    Dim index As Long
    
    If Not swModel Is Nothing Then
        drawingPath = swModel.GetPathName
        Debug.Print "Success = " & swModel.GetPathName
    End If
        
        
    Set swView = swDraw.GetFirstView
    Set swView = swView.GetNextView
    
    If Not swView Is Nothing Then
        asmPath = swView.GetReferencedModelName
        
        'DEBUGGING
        Debug.Print "Success = " & swView.GetReferencedModelName
        'END_DEBUGGING
        
        Set swModel = swApp.ActivateDoc3(asmPath, False, 0, 0)
        configurationNames = swModel.GetConfigurationNames
        swView.SetVisible False, False
        Set swModel = swApp.ActivateDoc3(drawingPath, False, 0, 0)
    End If
    
    For index = 0 To UBound(configurationNames)
        Dim bomTblAnnotation As SldWorks.BomTableAnnotation
        Dim bomStandard As String
        
        bomStandard = "C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\lang\english\bom-standard.sldbomtbt"
        Set bomTblAnnotation = swView.InsertBomTable3(False, 0, 0, swBOMConfigurationAnchor_BottomLeft, swBomType_TopLevelOnly, configurationNames(index), bomStandard, False)
    Next
    
    For index = 0 To UBound(configurationNames)
        Dim tempBom As SldWorks.BomTableAnnotation
        Dim swTblAnnotation As SldWorks.TableAnnotation
        Dim itemNumber As String
        Dim lowestItemNumber As String
        Dim partNumber As String
        Dim Part As New CustomPartInfo
        
        lowestItemNumber = "0"
        
        Dim i As Integer
        Dim j As Integer
        Dim k As Integer
        
        
        Set swTblAnnotation = bomTblAnnotation
        
        'DEBUGGING
        'Debug.Print "ConfigName: " & configurationNames(index)
        'Debug.Print "View: " & swView.GetName2
        'Debug.Print "Count: " & bomTblAnnotation.GetComponentsCount2(1, configurationNames(index), itemNumber, partNumber)
        'Debug.Print "Table Columns: " & swTblAnnotation.ColumnCount & " Table Rows: " & swTblAnnotation.RowCount
        'END_DEBUGGING
                        
        For i = 1 To swTblAnnotation.RowCount - 1
            bomTblAnnotation.GetComponentsCount2 i, configurationNames(index), itemNumber, partNumber
            If (lowestItemNumber < itemNumber) Then
                For k = 1 To swTblAnnotation.RowCount - 1
                    Dim vSwComponent As Variant
                    vSwComponent = bomTblAnnotation.GetComponents2(i, configurationNames(index))
                    
                    setAsm vSwComponent, Part
                    
                    Part.SetPartCount bomTblAnnotation.GetComponentsCount2(i, configurationNames(index), itemNumber, partNumber), CStr(configurationNames(index)), partNumber
                    Part.SetItemNumber (itemNumber)
                Next k
                lowestItemNumber = itemNumber
            Else
                Part.AddPartNames (partNumber)
            End If
            collectionPartInfo.Add Part, itemNumber
        Next i
    Next index
    
    swModel.ForceRebuild3 (True)
End Sub
